/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_resample_Resample */

#ifndef _Included_net_sourceforge_resample_Resample
#define _Included_net_sourceforge_resample_Resample
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sourceforge_resample_Resample_DEFAULT_BUFFER_SIZE
#define net_sourceforge_resample_Resample_DEFAULT_BUFFER_SIZE 4096L
#undef net_sourceforge_resample_Resample_MAX_CHANNELS
#define net_sourceforge_resample_Resample_MAX_CHANNELS 2L
#undef net_sourceforge_resample_Resample_CHANNEL_MONO
#define net_sourceforge_resample_Resample_CHANNEL_MONO 0L
#undef net_sourceforge_resample_Resample_CHANNEL_LEFT
#define net_sourceforge_resample_Resample_CHANNEL_LEFT 0L
#undef net_sourceforge_resample_Resample_CHANNEL_RIGHT
#define net_sourceforge_resample_Resample_CHANNEL_RIGHT 1L
/*
 * Class:     net_sourceforge_resample_Resample
 * Method:    downmix
 * Signature: ([S[S[SI)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_resample_Resample_downmix
  (JNIEnv *, jclass, jshortArray, jshortArray, jshortArray, jint);

/*
 * Class:     net_sourceforge_resample_Resample
 * Method:    resample
 * Signature: (D[S[SI)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_resample_Resample_resample
  (JNIEnv *, jclass, jdouble, jshortArray, jshortArray, jint);

/*
 * Class:     net_sourceforge_resample_Resample
 * Method:    initialize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_resample_Resample_initialize
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     net_sourceforge_resample_Resample
 * Method:    getFactor
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_net_sourceforge_resample_Resample_getFactor
  (JNIEnv *, jclass);

/*
 * Class:     net_sourceforge_resample_Resample
 * Method:    process
 * Signature: ([S[SIZ)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_resample_Resample_process
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jboolean);

/*
 * Class:     net_sourceforge_resample_Resample
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_resample_Resample_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
